### ISSUE TITLE
Database connection timeouts/performance issues

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#1]
@rob-baron has reported persistent problems with database connection timeouts while working with xdmod. In order to resolve these problems we need to better characterize the issue. There are several things we should do:

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [ ] #6
- [x] #7

I'm going to create separate issues for each of the above and assign them to folks. Please feel free to re-assigned if you think I've made the wrong choice.

**Comment by msdisme** [comment]
summary of the whole issue resolution: https://blog.oddbit.com/post/2022-09-10-kubernetes-labels/
