### ISSUE TITLE
Contents of alerts sent to alerts-nerc-ocp are missing data

### ISSUE THREAD

**Issue by aabaris** [OCP-on-NERC/operations#100]
URLs provided in alerts are invalid.  Some are missing all data.

For example:
https://massopencloud.slack.com/archives/C044ZCTUWCV/p1680039451537739

**Comment by aabaris** [comment]
![slack-alrt](https://user-images.githubusercontent.com/8989161/228374510-b11d6cc7-4c2e-4ac6-b95b-4b9e6bbb09ec.png)

**Comment by joachimweyl** [comment]
@computate is this something that you know how to fix or is it going to require some research?

**Comment by computate** [comment]
Yes @joachimweyl, I have been tweaking the alerts yesterday to get better messages into Slack, including this one much improved for Ceph. I'll try to improve the other ones as I work some more on these alerts. 
![image](https://user-images.githubusercontent.com/15114160/231225930-cbd87633-1c52-4664-bf66-ebc31af90a07.png)

**Comment by computate** [comment]
I have fixed the problem with missing content in alerts by grouping them properly with the fields required for each alert in this PR: https://github.com/OCP-on-NERC/nerc-ocp-config/pull/229
