### ISSUE TITLE
Find a solution for vault backup pod logins

### ISSUE THREAD

**Issue by dystewart** [OCP-on-NERC/operations#112]
Right now we're using the vault token to authenticate to vault from the backup pod

We're running into auth issues periodically (likely when the login session expires) which causes the backup job to fail. 

There are a few things we can do to resolve this (in no particular order):
1. Create a new login via OIDC or something else within vault specifically for the backup job
2. Extend the vault token login session

**Comment by larsks** [comment]
@dystewart maybe use [Kubernetes authentication](https://developer.hashicorp.com/vault/docs/auth/kubernetes) instead. That uses a Kubernetes service account token for authentication. We do this with the external secrets operator, for example.

**Comment by dystewart** [comment]
@larsks I think this makes sense, and it removes reliance on the use of any vault tokens

**Comment by joachimweyl** [comment]
@dystewart what are the next steps for this?

**Comment by dystewart** [comment]
@joachimweyl Still need to set up a job to use k8s auth as described above, haven't had the cycles to implement yet

**Comment by joachimweyl** [comment]
auto close from OCP-on-NERC/nerc-ocp-config#767 did not work. closing.
