### ISSUE TITLE
Simulate practical use cases  using the rhods deployment in the test cluster

### ISSUE THREAD

**Issue by dystewart** [OCP-on-NERC/operations#119]
With rhods now available in the test cluster we need to:

1. create an environment in rhods to test the student/academic use case (Danni and Ke recommend using this [image](quay.io/rh_ee_keli/ucsls:test-NERC-test))
2. There would be benefit to a Vanilla RHODS image to test in the test cluster

**Comment by joachimweyl** [comment]
@dystewart can you please provide details of how this is going?

**Comment by dystewart** [comment]
@joachimweyl in the test cluster we have deployed the ope image successfully along with a more basic rhods notebook. 

There was a perms issue with the ope image initially, which Ke has solved via expanding the group permissions within the container itself.  I'll be looking into other potential solutions to permissions issues issues like these, as the ope group is interested in learning more. 

Here are some blog posts explaining the permissions issue in detail as well as a couple fixes:
[https://cloud.redhat.com/blog/jupyter-on-openshift-part-6-running-as-an-assigned-user-id](https://cloud.redhat.com/blog/jupyter-on-openshift-part-6-running-as-an-assigned-user-id)
[https://cloud.redhat.com/blog/jupyter-openshift-part-2-using-jupyter-project-images](https://cloud.redhat.com/blog/jupyter-openshift-part-2-using-jupyter-project-images)

With the ope image up and running myself Danni and Ke can experiment further with the ope notebook.

**Comment by hpdempsey** [comment]
This is also the place where we had asked if @Milstein would like to run some of his Jupyter notebooks for testing the "regular" RHODS environment.  I think @joachimweyl  was going to follow up on whether that would be OK with NERC.

**Comment by joachimweyl** [comment]
@Milstein completed his testing May 10th
here is his feedback
1. Workbench working
1. Would be a good idea to use admin setting to stop containers after time frame
1. Noticed no GPU’s yet

**Comment by dystewart** [comment]
@joachimweyl We have one more test to run once the clusters are back online, @DanNiESh would like to run a stress test of sorts by scaling up the ope rhods image to something like 100 instances. This way we can get a real feel for the resource reqs

**Comment by dystewart** [comment]
At this point we've tested the rhods deployment in the nerc-ocp-test cluster thoroughly, including integrationand ops with the newly added gpus. As of now testing is largely wrapped up in the test cluster for rhods
