### ISSUE TITLE
Set up auth and RBAC for new groups using test cluster

### ISSUE THREAD

**Issue by dystewart** [OCP-on-NERC/operations#125]
We need to add users from a few teams to the NERC github org for github auth. Users that will need adding to the org for now are:

1. nerc-rhods: gagansk computate okrieg hpdempsey DanNiESh like101101 griffinandrew
2. nerc-ai4cloudops: syedmohdqasim
3. nerc-curator: skanthed gagansk TRudenko22

The RBAC for these groups also needs implementing from the OpenShift side which I am working on now. Each user in these groups will be getting admin access to their respective namespaces.

**Comment by dystewart** [comment]
Project namespaces will also need to be created for:

1. aiops: ai4cloudops
2. curator: curator-operator

**Comment by dystewart** [comment]
@larsks I updated the groups above to include the github usernames as requested

**Comment by larsks** [comment]
@dystewart I've create the github teams and populated them as requested, except for `nerc-ai4cloudops` for which I still need the github username(s).

**Comment by dystewart** [comment]
@larsks thanks! Just updated ai4cloudops username

**Comment by dystewart** [comment]
@larsks A few more users and groups that still need adding:

Add group and users:
nerc-ai4cloudops: syedmohdqasim, zaoxing

Add user:
nerc-rhods: nathanweeks

**Comment by larsks** [comment]
I've added all of the above!

**Comment by joachimweyl** [comment]
@dystewart is this issue now resolved?

**Comment by dystewart** [comment]
We'll need to add:
nerc-rhods: syedmohdqasim, zaoxing

**Comment by larsks** [comment]
@dystewart I've added these folks to the `nerc-rhods` group.

**Comment by dystewart** [comment]
@larsks can we add:
nerc-rhods: zongshun96

**Comment by joachimweyl** [comment]
@dystewart zongshun96 is already there I added him yesterday.
