### ISSUE TITLE
timeouts when acessing infra-cluster

### ISSUE THREAD

**Issue by aabaris** [OCP-on-NERC/operations#127]
We are experiencing authentication errors when trying to access nerc-ocp-infra cluster.  Errors are intermittent, they are almost constant when accessing via web console and infrequent but present when accessing via CLI.  They appear to exhibit timeout like behavior.  When trying to log in via web console, most common outcome is a long wait followed by a simple message stating "An authentication error occurred."

**Comment by aabaris** [comment]
In addition, when trying to access vault instance running on infra using my github  credentials I get authorization error. 

```
{"error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.","state":"vvxszjes5i33ibg4yowahurwf"}
```

I find it highly likely that this is related.

**Comment by dystewart** [comment]
I have been able to log in as kubeadmin user today, but the login took well over a minute to complete.

**Comment by jtriley** [comment]
> @aabaris @jtriley is there a red hat case open on this?

https://access.redhat.com/support/cases/#/case/03513513

**Comment by jtriley** [comment]
Merging https://github.com/OCP-on-NERC/nerc-ocp-config/pull/242 appears to have fixed this issue.
