### ISSUE TITLE
Need account to read production metrics

### ISSUE THREAD

**Issue by tzumainn** [OCP-on-NERC/operations#13]
In order for XDMoD to grab the required infomation, I'll need an account that can read those metrics.

**Comment by joachimweyl** [comment]
@jtriley and @larsks what would be the best way to ensure @tzumainn receives the account that he needs?

**Comment by joachimweyl** [comment]
Blocked on Production.

**Comment by naved001** [comment]
@larsks @tzumainn what namespace will the serviceaccount be in? For the MOC ocp-staging cluster the serviceaccount was in xdmod-tzumainn namespace.

**Comment by tzumainn** [comment]
Ah, I don't know what a "professional" account might sound like; I assume we don't want my name in this? Does something like 'xdmod-metrics' work or are there some other constraints?

**Comment by naved001** [comment]
in the [draft PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/105) I have called the namespace `xdmod`.

**Comment by tzumainn** [comment]
Makes sense to me!

**Comment by naved001** [comment]
@tzumainn @rob-baron I have put the serviceaccount token in vault at `nerc-ocp-infra/xdmod/nerc-ocp-prod-xdmod-reader` with the key `token`.
