### ISSUE TITLE
Refine list of Field of Science for usage metrics

### ISSUE THREAD

**Issue by joachimweyl** [OCP-on-NERC/operations#136]
[Here](https://github.com/ubccr/coldfront/blob/main/coldfront/core/field_of_science/management/commands/data/field_of_science_data.csv) is the full list.
we would like to narrow this down.
maybe use the [NSF Classification guide](https://osp.unm.edu/pi-resources/nsf-research-classifications.html) as a starting place.
Need to also include biomedical, public health, business, and a few others
NIH analogous headings
some details from this [Slack conversation](https://massopencloud.slack.com/archives/CNMSRMDA5/p1676496634798889).
This [Spreadsheet](https://docs.google.com/spreadsheets/d/1wtKMQrkbOd3wNq1vnYercTImJRuhHwR_R842TY7W6Aw/edit#gid=0) has the mapping.

**Comment by joachimweyl** [comment]
@waygil & @syockel please review and refine the ColdFront list and create mappings
for example
| ColdFront FoS | Refined FoS |
| long name 1 | FoS1 |
| long name 2 | FoS1 |
| long name 3 | FoS2 |
| long name 4 | FoS2 |
| long name 5 | FoS2 |
| long name 6 | FoS2 |
| long name 7 | FoS3 |

**Comment by joachimweyl** [comment]
@waygil, @syockel, & @Milstein? Who is the best of the 3 of you to work on this?

**Comment by joachimweyl** [comment]
The Coldfront list is the list by Project
XDMod is currently using the field of science by PI

**Comment by syockel** [comment]
Kim I already mapped those here <https://docs.google.com/spreadsheets/d/1wtKMQrkbOd3wNq1vnYercTImJRuhHwR_R842TY7W6Aw/edit#gid=0>.
