### ISSUE TITLE
Authentication Error When Login RHODS Test Cluster with Github Account

### ISSUE THREAD

**Issue by Zongshun96** [OCP-on-NERC/operations#137]
Hello,
I am trying to get access to RHODS in the test cluster for my summer project but facing the `authentication error` when login with my Github Account. [Here](https://massopencloud.slack.com/archives/CNMSRMDA5/p1685712748973809?thread_ts=1685111293.199119&cid=CNMSRMDA5) and [here](https://massopencloud.slack.com/archives/C058F3UEYGN/p1685568226931799?thread_ts=1685565930.065099&cid=C058F3UEYGN) are the slack threads related to this issue.

![Screen Shot 2023-06-02 at 12 43 57 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/1d43c1c8-1954-4977-8990-e42c0037b390)

I have connected to the harvard VPN using my account `zhangzs@nerc` and I have been added to the RHODS team.
I also tried to login in an Incognito window but still didn't work.
Please advise what I can do to fix the problem.
Many thanks!

Best,
Zongshun

**Comment by larsks** [comment]
The test cluster is currently configured to allow logins only to members of the `nerc-ops` and `nerc-logs-metrics` teams.  See [the oauth configuration](https://github.com/OCP-on-NERC/nerc-ocp-config/blob/main/cluster-scope/overlays/nerc-ocp-test/oauths/cluster_patch.yaml#L14):

```
        teams:
          - ocp-on-nerc/nerc-ops
          - ocp-on-nerc/nerc-logs-metrics
```

I'll submit a PR to broaden that list.
