### ISSUE TITLE
Accessing Logs for Container Images Pulled

### ISSUE THREAD

**Issue by Zongshun96** [OCP-on-NERC/operations#139]
For my summer project, I need to do a case study regarding the frequently installed packages in those pulled container images in NERC. However, I was only able to get access to the the application logs (which won't tell me the images pulled) but not the Infra or Audit logs. @computate told me that [role based access control to Loki is under developping](https://github.com/OCP-on-NERC/operations/issues/124). So is there a workaround for me to retrieve the logs for images pulled in NERC?
Many thanks!
Zongshun

**Comment by computate** [comment]
@Zongshun96 I do have a workaround. After the NERC shutdown period is over, please let me know if you do not have permissions to obtain the `logcollector-token`, and I will discuss with the NERC team about sharing this token with you. Here is how to access the infrastructure and audit logs by obtaining the logcollector-token like this:

```bash
$ LOKI_TOKEN=$(oc --as system:admin -n openshift-logging get secret/logcollector-token -o jsonpath={.data.token} | base64 -d)
$ LOKI_BASE_URL=https://$(oc --as system:admin -n openshift-logging get route/logging-loki -o jsonpath={.spec.host})
$ LOKI_LOG_TYPE=infrastructure
$ LOG_DURATION="1 hour"
$ LOG_START=$(date -u -d "$LOG_DURATION ago" '+%s%N')
$ LOG_END=$(date -u '+%s%N')
$ LOG_LIMIT=100
$ curl -H "Authorization: Bearer $LOKI_TOKEN" "$LOKI_BASE_URL/api/logs/v1/$LOKI_LOG_TYPE/loki/api/v1/query_range?query=%7B+log_type%3D%7E%22.%2B%22+%7D+%7C+json&start=$LOG_START&end=$LOG_END&limit=$LOG_LIMIT"
```

**Comment by Zongshun96** [comment]
@computate I think I don't have the `logcollector-token`. Can you see if I can get permission for that? Thanks.
```
ubuntu@test-retrieving-logs:~$ oc --as system:admin -n openshift-logging get secret/logcollector-token -o jsonpath={.data.token} | base64 -d
error: the server doesn't have a resource type "secret"
```

**Comment by Zongshun96** [comment]
I only used Grafana data for my project at the end. I created a [RP](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/255) to add `kube_pod_container_info` to monioring and now my pipeline is able to retrieve the image info from ACM/Grafana.
https://github.com/ai4cloudops/Praxi-Pipeline/blob/7fac19b79ac56f41b098d5adb380a510038f3ddf/get_layer_changes/src/read_layered_image.py#L51
