### ISSUE TITLE
Figure out why keycloak connection isn't working

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#15]
After @knikolla's ocp-on-nerc/nerc-ocp-config#63 merged, we are seeing the following in the logs for the authentication-operator pod:

```
authentication-operator-7449fd4467-j4rbf authentication-operator E1013 13:47:28.510112       1 base_controller.go:272] ConfigObserver reconciliation failed: failed to apply IDP mss-keycloak config: dial tcp 140.247.152.15:443: i/o timeout
```

This is likely a firewall issue somewhere; @jtriley can probably confirm.

**Comment by jtriley** [comment]
Looking into it - I can confirm I can't connect from a debug pod running on controller hosts in `nerc-ocp-prod`.

**Comment by jtriley** [comment]
Should be fixed:

```
sh-4.4# nc -w 2 -v 140.247.152.15 443
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 140.247.152.15:443.
```
Let me know if you still have issues.

**Comment by joachimweyl** [comment]
@knikolla can you confirm you are no longer receiving the error?

**Comment by knikolla** [comment]
Everything works. Fixed by https://github.com/OCP-on-NERC/nerc-ocp-config/pull/122
