### ISSUE TITLE
RHODS Pipelines in Test Cluster Is Not Working

### ISSUE THREAD

**Issue by Zongshun96** [OCP-on-NERC/operations#152]
## Symptons
The current version of RHODS in test cluster is 1.28.0, which should includes the RHODS Pipelines. And we also observed the RHODS pipeline operator service and pod running. However I was not able to access the Pipelines application through the RHODS Dashborad nor in the JupyterLab. I have been contacting with @dystewart and @DanNiESh regarding this issue. While @dystewart is working on a solution (big thank you), I am popping an issue to track and gain more exposure for this problem.

Heidi mentioned that @Milstein had ran a ML model with RHODS before (not sure if that was done with Pipeline or the model serving function in RHODS). Does @Milstein have any insight about this issue? Thank you!

### Screenshots

- RHODS Version
![Screen Shot 2023-06-22 at 1 21 38 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/631cd728-0957-4ffe-86cb-25225b9480f0)

- RHODS Pipeline Operator Pod
![Screen Shot 2023-06-22 at 1 22 08 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/b1e1c44c-6cbb-4ab5-9566-2138326bdf85)

- RHODS Pipeline Operator Service
![Screen Shot 2023-06-22 at 1 19 35 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/f47297f9-eb8d-4a49-8c05-116e80bae40f)

- RHODS Pipeline Dashborad
![Screen Shot 2023-06-22 at 10 23 30 AM](https://github.com/OCP-on-NERC/operations/assets/34226180/adc1c19b-8e9c-459c-a37e-95496401c00e)

## Context
My project aims to deploy a Software Discovery service using RHODS Pipelines. This service will scan vulnerable depandancies(packages) in container images using a ML method based on installation footprints. In this way, it is more flexible comparing to manual rule-based approach (e.g., file hashing), while tradeoffing the accuracy.

**Comment by hpdempsey** [comment]
@Milstein  reported the same missing pipelines operator issue yesterday too.  This is probably first time he tried to use it since the rebuild.  Asking for RHODS eng help on this one.

**Comment by Zongshun96** [comment]
@dystewart and @hpdempsey had a meeting with RHODS people. (Big thank you! ☺️ ) It is a bug of RHODS and only observed in the test cluster after the NERC downtime. Dylan is working on a workaround.

**Comment by Zongshun96** [comment]
This problem in test cluster is fixed now and it seems to be an known issue in RHODS 1.28 
https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.28/html/1.28_release_notes/known-issues_relnotes#known-issues_RHODS-9583_relnotes

More discussion regarding this specific fix was on internal slack. 
https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1688394632147809?thread_ts=1688040399.420519&cid=C03UGJY6Z1A
