### ISSUE TITLE
prod and test clusters are in "Unknown" state in argocd settings

### ISSUE THREAD

**Issue by jtriley** [OCP-on-NERC/operations#153]
Both the prod and test clusters are current in an `Unknown` state in argocd settings. The only prod-related application that shows up within the argocd UI is the `nerc-ocp-prod-aoa` app which is also out-of-sync.

<img width="653" alt="Screenshot 2023-06-28 at 3 47 55 PM" src="https://github.com/OCP-on-NERC/operations/assets/46910/128cc5a4-5b32-4601-92ad-69ad3e7284ea">

As a quick check I'm able to curl the API address for prod from the application controller prod in the `openshift-gitops` namespace.

Both the prod and test clusters show in the ACM dashboard as `Ready` with a green check mark. It also shows their version, number of nodes, upgrade status, etc. correctly AFAICT.

**Comment by joachimweyl** [comment]
@jtriley is this still an issue?

**Comment by jtriley** [comment]
I was able to resolve it just now just by syncing the app-of-app repos for prod and test. Apparently, if there aren't any applications defined for a cluster it shows up as Unknown (see: https://github.com/argoproj/argo-helm/issues/446#issuecomment-720100790). Not clear yet why applications fell off but syncing things seems to have resolved the issue.
