### ISSUE TITLE
observability-controller degraded on prod cluster and no prod metrics sent to ACM

### ISSUE THREAD

**Issue by computate** [OCP-on-NERC/operations#162]
Since before Thu Jun 29. 2023, the [observability-controller on the prod cluster is degraded](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/multicloud/infrastructure/clusters/details/nerc-ocp-prod/settings). @jtriley resolved another alert related to the [image-registry operator ImagePrunerJobFailed which you can see here](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Observatorium%22,%7B%22exemplar%22:true,%22expr%22:%22ALERTS%7Balertname%3D%5C%22ClusterOperatorDegraded%5C%22%7D%22%7D%5D), but it did not resolve the observability-controller degraded problem. See these [logs in the Prod cluster 
`oc -n open-cluster-management-addon-observability logs -l component=metrics-collector --since=1h` 
where the metrics-collector cannot connect to a host: 

`level=error caller=logger.go:55 ts=2023-07-05T19:22:35.830120401Z component=forwarder/worker msg="unable to forward results" err="Get \"https://prometheus-k8s.openshift-monitoring.svc:9091/...": dial tcp 172.30.6.221:9091: connect: no route to host"`

**Comment by jtriley** [comment]
@computate After some debugging I think I've narrowed this down to an issue with the host the pods in the `open-cluster-management-addon-observability` namespace were currently running on (`node/wrk-42`). I cordoned that node and deleted the operator and metrics collector pod in that namespace and it appears to be progressing now. 🤞

**Comment by jtriley** [comment]
Seems that did the trick. Going to close the issue for now.
![Screenshot 2023-07-06 at 12 55 48 PM](https://github.com/OCP-on-NERC/operations/assets/46910/569128c5-beac-45b8-b299-7d4a559cb728)
