### ISSUE TITLE
Configure ODF on production cluster

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#17]
We need ODF configured to provide PV and ObjectBucket support to the production cluster.

**Comment by jtriley** [comment]
The pools and access keys for prod have already been created on NESE a while ago. @larsks should have those details

**Comment by larsks** [comment]
@jtriley the issue is that we will probably require changes to ceph permissions vs. what was originally requested (as we did for infra and the smaug cluster).

**Comment by jtriley** [comment]
@larsks Those ceph client permission changes should be in place now. - let me know if you have issues.
