### ISSUE TITLE
To gather the hardware info for the V100 machines and update the base SU rate of per hour wall time

### ISSUE THREAD

**Issue by Milstein** [OCP-on-NERC/operations#178]
We have to update the [service description](https://docs.google.com/document/d/1I_HL-wopbzH5VhxvsBoxFKkRIEcyY_pPG5T8f1zuFRc/edit) with the rate.

**Comment by Milstein** [comment]
> This does not match the current plan for the new V100 flavor definition:
> v100.1 (24 HT cores/96GB) v100.1m (48 HT cores/192GB)
> Should revisit and adjust as needed to match actual hw (40core/80HT 768GB mem total).

**Comment by joachimweyl** [comment]
@syockel or @waygil do we know how much it would cost to replace the V100 Machines we currently have? In other words, we need to price what we should charge for the V100 SU and need to know the cost of the unit to get that value.

**Comment by joachimweyl** [comment]
50% of A100 cost is now in the [Invoicing Requirements](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1) Doc.
