### ISSUE TITLE
Gather information about the failing database queries

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#2]
Enable query logging in mariadb and record the queries that result in the connection timeouts.

**Comment by larsks** [comment]
@rob-baron in addition to the mariadb query logs, it would be great if you could also add (either here directly or as a link to content elsewhere) instructions for spinning up the xdmod image, mariadb, and some sample data, and then use that environment with some sample data in a way that reproduces the problem at least some of the time.

**Comment by larsks** [comment]
Here is the original error description: https://github.com/CCI-MOC/xdmod-cntr/issues/67

**Comment by rob-baron** [comment]
There are 2 things that larsks is asking for:

1) A way to replicate the problem, of which is here (https://github.com/CCI-MOC/debugConnectionTimeout) - instructions are in the README.

2) to enable query logging

I will add the things needed to enable what I think he is asking for to the aforementioned repo.

**Comment by larsks** [comment]
For folks looking to use the above mentioned reproduction repository, note that it requires an in-cluster image (`image-registry.openshift-image-registry.svc:5000/test001/moc-xdmod`) that is only available on the `ocp-staging` cluster.

**Comment by larsks** [comment]
Running the reproducer, I ran into a *different* failure:

```
Traceback (most recent call last):
  File "/usr/bin/xdmod-init", line 418, in <module>
    main()
  File "/usr/bin/xdmod-init", line 314, in main
    xdmod_setup_database(xdmod_init_json["database"])
  File "/usr/bin/xdmod-init", line 112, in xdmod_setup_database
    run_pexpect_json(xdmod_setup_databases_json)
  File "/usr/bin/xdmod-init", line 147, in run_pexpect_json
    setup.expect(prompt_resp["prompt"], timeout=time_out)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.6/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.6/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f57cf4e1f98>
command: /usr/bin/xdmod-setup
args: ['/usr/bin/xdmod-setup']
buffer (last 100 chars): b'base `mod_logger`.\r\nCreating database `mod_logger`.\r\nGranting privileges on database `mod_logger`.\r\n'
before (last 100 chars): b'base `mod_logger`.\r\nCreating database `mod_logger`.\r\nGranting privileges on database `mod_logger`.\r\n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 23
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b"Overwrite config file '/etc/xdmod/portal_settings.ini' \\(yes, no\\)\\? \\[.*\\]")
```

@rob-baron have you seen that before? Looks like the expect module timing out waiting for a prompt, which could be a real timeout or could be some unexpected output throwing off. I'm increasing the timeout value on line 147 to see if I can get past this point.

**Comment by rob-baron** [comment]
That reminds me, I didn't initially have to use the complete internal registry address, (ie, image-registry.openshift-image-registry.svc:5000/test001/moc-xdmod) I could just use 'moc-xdmod'.  I though it was set up to look at the internal registry then docker, however,  now it seems to look at docker first.

-- or am I missing something?

**Comment by rob-baron** [comment]
@larsks did the database mod_logger get created?

**Comment by larsks** [comment]
I'm redeploying things right now; I'll let you know in a few.

**Comment by larsks** [comment]
@rob-baron I have a question about the instructions in the `README`, which say:

>- then run
>
>  ```
>  % xdmod-init
>  ```

Doesn't the init container *already* run `xdmod-init`? So by the time we've logged into the live container, the command has already been run and the databases are populated, etc.

**Comment by larsks** [comment]
Ah, never mind; I see that the initial execution is just copying some files around.

**Comment by larsks** [comment]
I seem to have gotten farther this time, but now it's failing with:

```
Create the file share database
set server_root in /etc/httpd/conf/httpd.conf
   Ingesting resources
tar: Removing leading `/' from member names
 Writing /etc/xdmod/etc_xdmod.b64 to db
bash-4.2$ PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/log/xdmod/etl_overseer.log" could not be opened in append mode: chmod(): Permission denied' in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110
Stack trace:
#0 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#1 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /usr/share/xdmod/classes/CCR/Logger.php(37): Monolog\Logger->addRecord(400, '{"message":"The...', Array)
#3 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(698): CCR\Logger->addRecord(400, 'The stream or f...', Array)
#4 /usr/share/xdmod/tools/etl/etl_overseer.php(631): Monolog\Logger->err('The stream or f...')
#5 /usr/share/xdmod/tools/etl/etl_overseer.php(612): log_error_and_exit('The stream or f...')
#6 {main}
  thrown in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 110
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/log/xdmod/etl_overseer.log" could not be opened in append mode: chmod(): Permission denied' in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110
Stack trace:
#0 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#1 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /usr/share/xdmod/classes/CCR/Logger.php(37): Monolog\Logger->addRecord(500, '{"message":"Unc...', Array)
#3 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(726): CCR\Logger->addRecord(500, Array, Array)
#4 /usr/share/xdmod/classes/CCR/Log.php(128): Monolog\Logger->crit(Array)
#5 [internal function]: CCR\Log::CCR\{closure}()
#6 {main}
  thrown in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 110
```

**Comment by larsks** [comment]
Okay, here is the actual database failure:

```
Failed to create databases:

Command returned non-zero value '1': ERROR 2003 (HY000): Can't connect to MySQL server on 'mariadb' (110)

#0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(521): CCR\DB\MySQLHelper::staticExecuteCommand(Array)
#1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(332): CCR\DB\MySQLHelper::staticExecuteStatement('mariadb', '3306', 'root', 'pass', NULL, 'SELECT SCHEMA_N...')
#2 /usr/share/xdmod/classes/OpenXdmod/Shared/DatabaseHelper.php(65): CCR\DB\MySQLHelper::databaseExists('mariadb', '3306', 'root', 'pass', 'mod_logger')
#3 /usr/share/xdmod/classes/OpenXdmod/Setup/DatabaseSetupItem.php(39): OpenXdmod\Shared\DatabaseHelper::createDatabases('root', 'pass', Array, Array, Object(OpenXdmod\Setup\Console))
#4 /usr/share/xdmod/classes/OpenXdmod/Setup/DatabaseSetup.php(109): OpenXdmod\Setup\DatabaseSetupItem->createDatabases('root', 'pass', Array, Array)
#5 /usr/share/xdmod/classes/OpenXdmod/Setup/Menu.php(69): OpenXdmod\Setup\DatabaseSetup->handle()
#6 /usr/bin/xdmod-setup(37): OpenXdmod\Setup\Menu->display()
#7 /usr/bin/xdmod-setup(22): main()
#8 {main}

Settings file not saved!
```

**Comment by larsks** [comment]
Well, this is interesting. Logged into the node on which mariadb is running, trying to run `crictl pods` is failing with:

```
[root@neu-17-39 ~]# crictl pods
FATA[0000] listing pod sandboxes: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4667581 vs. 4194304)
```

**Comment by larsks** [comment]
That error from `crictl pods` may just be https://github.com/kubernetes-sigs/cri-tools/issues/872

**Comment by larsks** [comment]
Here's another interesting tidbit. If I run the following loop in the xdmod container:

```
while :; do
  _start=$SECONDS
  echo -n "$(date +%T) "
  timeout 5 mysql -h mariadb -uroot -ppass -e 'select 1' > /dev/null && echo -n OKAY || echo -n FAILED
  echo " $(( SECONDS - _start))"
  sleep 1
done
```

Then I see as output:

```
22:58:12 OKAY 0
22:58:13 FAILED 5
22:58:19 OKAY 3
22:58:23 OKAY 1
22:58:25 OKAY 2
22:58:28 OKAY 3
22:58:32 OKAY 3
22:58:36 OKAY 0
22:58:37 OKAY 0
22:58:38 OKAY 0
22:58:39 OKAY 0
22:58:40 OKAY 1
22:58:42 OKAY 1
22:58:44 OKAY 1
22:58:46 OKAY 1
22:58:48 OKAY 1
22:58:50 OKAY 1
22:58:52 OKAY 0
22:58:53 OKAY 0
22:58:54 OKAY 0
22:58:55 OKAY 0
22:58:56 OKAY 0
22:58:57 OKAY 1
22:58:59 OKAY 1
22:59:01 OKAY 0
22:59:02 OKAY 1
22:59:04 OKAY 0
22:59:05 FAILED 5
22:59:11 OKAY 3
22:59:15 FAILED 5
22:59:21 OKAY 1
22:59:23 FAILED 5
22:59:29 FAILED 5
22:59:35 FAILED 5
22:59:41 FAILED 5
22:59:47 OKAY 1
22:59:49 OKAY 0
22:59:50 OKAY 0
22:59:51 OKAY 0
22:59:52 OKAY 0
22:59:53 OKAY 1
22:59:55 OKAY 0
22:59:56 FAILED 5
```

So there is a lot of variability in the time it takes to connect (on a
system that is mostly idle).

**Comment by larsks** [comment]
The timeouts were due to misconfigured labels in the manifests. I've put together an extended write-up [here](https://blog.oddbit.com/post/2022-09-10-kubernetes-labels/), but the tl;dr is that `spec.selector` in both the Deployment and the Service needs to uniquely identity the target pod. As currently configured, all the pods produced by these manifests have identical labels, so the load balancer will sometimes attempt to send traffic targeting `mariadb` to the wrong pod.

**Comment by larsks** [comment]
I've submitted https://github.com/CCI-MOC/debugConnectionTimeout/pull/1 to show the changes I had to make in order to correct the problem in the demo repository.

**Comment by rob-baron** [comment]
modifying @lrsks script and using time instead of timeout, and letting it run on the mariadb pod for some time (haven't processed the data yet) yielded the following:

        real	0m1.056s
        user	0m0.002s
        sys	0m0.004s
        ERROR 2003 (HY000): Can't connect to MySQL server on 'mariadb' (110)
        
        real	2m9.299s
        user	0m0.001s
        sys	0m0.005s
        ...
        real	0m3.106s
        user	0m0.003s
        sys	0m0.004s
        ERROR 2003 (HY000): Can't connect to MySQL server on 'mariadb' (110)
        
        real	2m9.171s
        user	0m0.002s
        sys	0m0.003s

I managed to capture 4 such events.
