### ISSUE TITLE
Connect public VLAN to nerc-ocp-prod workers

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#20]
In order to support public access to services hosted on nerc-ocp-prod, we need to ensure that a public network is connected to all the nerc-ocp-prod worker nodes.

**Comment by jtriley** [comment]
I believe the public vlan has been trunked to the controllers but perhaps not for the worker nodes. Will check in on this today.

**Comment by jtriley** [comment]
Verified with network ops that the public net is indeed trunked as a tagged vlan to all controllers and worker nodes in the `nerc-ocp-prod` cluster.

**Comment by larsks** [comment]
@jtriley just confirming; that's vlan id 2178 (199.94.61.0/24), correct? What's the process for allocating addresses on that network?

**Comment by jtriley** [comment]
> @jtriley just confirming; that's vlan id 2178 (199.94.61.0/24), correct? What's the process for allocating addresses on that network?

Correct CIDR, but ID is 2180 (see also https://github.com/OCP-on-NERC/docs/pull/36). Process is DHCP, same as the other nets. Currently only the controllers are defined though - I can add an IP for all worker hosts if that's required?
