### ISSUE TITLE
Create wildcard DNS entry for *.apps.shift.nerc.mghpcc.org

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#22]
After allocating an address for the public ingress controller (#21), we need to create a wildcard DNS entry so that `<anything>.apps.shift.nerc.mghpcc.org` will map to that address. (I'm not wedded to that domain name if folks prefer something else; that's just what's currently configured in the external ingresscontroller manifest).

**Comment by jtriley** [comment]
This is in place already:

```
% dig +short test.apps.shift.nerc.mghpcc.org
199.94.61.6
```

**Comment by larsks** [comment]
I think we're going to need to run our own set of `keepalived` pods to manage the public vip.
