### ISSUE TITLE
See if we can reproduce the connection timeouts when using local storage

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#3]
One theory is that our problems are caused by performance issues with NESE storage. Let's see if the problems persist when using local storage.

**Comment by larsks** [comment]
@rob-baron I think you've already done this. Can you confirm that you saw the same problem using local storage for mariadb?

**Comment by rob-baron** [comment]
I was able to replicate some aspects of this via connecting mariadb to an ephemeral disk.
