### ISSUE TITLE
Re-install nerc-ocp-prod cluster

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#32]
Now that we've met most of our configuration goals for the nerc-ocp-prod cluster, we'd like to rebuild it for two reasons:

1. The cluster was inadvertently installed with OCP 4.11 earlier in the year, and
2. We want to demonstrate that the cluster *can* be rebuilt (and address any issues that crop up during the attempt).

**Comment by hpdempsey** [comment]
Were we still going to try doing this on the test cluster first with @computate?  Justin said he didn't need the servers that were meant for the test cluster on his investigation anymore, so this is in option if we want to pursue it.

**Comment by hpdempsey** [comment]
Thanks for the detailed summary @larsks and thanks to @naved001 @dystewart @jtriley for moving this ahead!
