### ISSUE TITLE
Verify that we don't have network connectivity issues (packet loss, interface errors, etc)

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#5]
Because we're using network-backed storage in the NERC environment, and we have seen some odd network behavior in the past, we should verify that we're not seeing issues in our underlying network connectivity. Are there interface errors? Packet loss? What else should we be looking at?

**Comment by naved001** [comment]
> I believe that's expected at this point

okay, thanks.

FWIW, I ran `nload` to  get average bandwidth usage and that didn't really indicate any bandwidth issues. After a 10 minute run the average bandwidth for each host was:

| host | Incoming (MBit/s) | Outgoing (MBit/s) | Total (MBit/s) |
| -----|----------|-----------|-----|
| ctl-0 | 16.37 | 55.38 | 71.75 | 
| ctl-1 | 13.70 | 52.96 | 66.66 |
| ctl-2 | 88.15 | 20.65 | 108.8 |

**Comment by larsks** [comment]
@naved001  I think we can close this issue for now (everything looks healthy), unless you were planning on looking at anything else.
