### ISSUE TITLE
Manage node labels via our configuration repository

### ISSUE THREAD

**Issue by naved001** [OCP-on-NERC/operations#50]
Various aspects of our OpenShift environment depend on labels being applied to Node resources.

We are currently [manually applying these labels](https://github.com/OCP-on-NERC/operations/issues/28#issuecomment-1317738000). We would like to manage node labels through our gitops workflow, both so that we have the change history and so that when we rebuild a cluster the appropriate labels are re-applied to nodes without requiring manual intervention.

**Comment by naved001** [comment]
We need to apply `"cluster.ocs.openshift.io/openshift-storage": "",` on all worker nodes to get noobaa running on both `nerc-ocp-infra` and `nerc-ocp-prod` clusters.

`"nerc.mghpcc.org/external-ingress": "true",` label goes on certain worker nodes of the `nerc-ocp-prod` cluster. @larsks how do we decided which nodes get this label and which don't? Also, what other labels do we apply manually?

**Comment by larsks** [comment]
> how do we decided which nodes get this label and which don't?

It's just a static list (it is basicaly, "those to nodes to which we've trunked the external VLAN").

> Also, what other labels do we apply manually?

I think that may be it right now.
