### ISSUE TITLE
Explore auto-backups from within vault

### ISSUE THREAD

**Issue by dystewart** [OCP-on-NERC/operations#53]
We're currently creating backups via a cronjob but I've seen a method we might be able to use from within vault: [https://developer.hashicorp.com/vault/tutorials/standard-procedures/sop-backup#automated-backup-procedures](https://developer.hashicorp.com/vault/tutorials/standard-procedures/sop-backup#automated-backup-procedures)

If this works as advertised it would simplify the backup process quite a bit, and we'd just need the cronjob to move the backup files out of vault (to the pvc and bucket storage)

**Comment by larsks** [comment]
This might even be easier than you think...it looks like the automatic snapshot facility may be able to write directly to an S3 bucket: https://developer.hashicorp.com/vault/tutorials/raft/raft-storage#automated-snapshots

**Comment by larsks** [comment]
@dystewart my reading of the docs is that we can't use this feature. Can you take a look and let me know if you agree? If so we should close this issue.

**Comment by dystewart** [comment]
@larsks Can confirm that this is a vault Enterprise only feature, closing this issue.
