### ISSUE TITLE
Capture system logs in loki

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#56]
As an administrator responsible for the underlying hardware and operating system, I want to collect system logs (e.g., the contents of the system journal) in loki so that I can correlate application issues with system-level problems (like disk errors, OOM killer activity, etc).

**Comment by computate** [comment]
The systemd journal logs are already available in the `infrastructure` logs in Loki with a query of `{tag="journal.system"}`. You can query the [systemd journal logs here](https://logging-grafana.apps.nerc-ocp-infra.rc.fas.harvard.edu/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22infrastructure-logging%22,%7B%22expr%22:%22%7Btag%3D%5C%22journal.system%5C%22%7D%22%7D%5D). I will close this issue, but feel free to reopen it if you find other system logs you are in need of.
