### ISSUE TITLE
Ensure we document URLs for all of the observability components

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#57]
Make sure it's easy to find everything we need to access observability components -- e.g., a collection of dashboards, etc. Just asks, "can we get to this from the OpenShift console, or do we just have to know where these things are?"

**Comment by computate** [comment]
Here is a PR to put Monitoring and Logging and quick links into one place: 
https://github.com/OCP-on-NERC/docs/pull/46
