### ISSUE TITLE
Unable to create new OBC on nerc-ocp-infra

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#60]
I attempted to create a new ObjectBucketClaim on nerc-ocp-infra and the resource got stuck in the "Pending" state:

```
NAME                        STORAGE-CLASS                 PHASE     AGE
storage-benchmark-results   openshift-storage.noobaa.io   Pending   12m
```

The Noobaa backing store seems okay:

```
NAME                           TYPE      PHASE   AGE
metrics-backing-store          pv-pool   Ready   126d
noobaa-default-backing-store   pv-pool   Ready   168d
```

The `metrics-backing-store` pool is almost full, but the OBC is being allocated from the `noobaa-default-backing-store`, which has ample space available.

Not sure what's going on here; I'm going to open a support case for this.

**Comment by computate** [comment]
@larsks I don't know if this is related, but I was trying to understand why the `metrics-backing-store` `BackingStore` points to the `storageClass: ocs-external-storagecluster-ceph-rbd` when nothing points to the `metrics-bucket-storage` `StorageClass` which states `description: Provides Object Bucket Claims (OBCs) specifically for metrics/logging`. Is the `metrics-backing-store` storageClass correct, or is there some kind of conflict? https://github.com/OCP-on-NERC/nerc-ocp-config/blob/main/cluster-scope/overlays/nerc-ocp-infra/metrics-bucket-storage/backingstore.yaml

**Comment by larsks** [comment]
@computate The `metrics-bucket-storage` storageclass is for ObjectBuckets. There is one OBC deployed on it right now:

```
$ kubectl -n openshift-operators-redhat get obc
NAME                                           STORAGE-CLASS            PHASE   AGE
openshift-operators-redhat-objectbucketclaim   metrics-bucket-storage   Bound   85d
```

We *should* be using that for anything related to observability; if you're deploying buckets on the default `openshift-storage.nooba.io` storageclass, you'll run out of space because there's only 50GB total available there. It doesn't look like much storage has been allocated from the default class so we seem to be in good shape on that front.

**Comment by larsks** [comment]
I have opened https://access.redhat.com/support/cases/#/case/03395419 on this issue.

**Comment by larsks** [comment]
The response to the support case starts with:

> 1. Scale operators: oc scale deployment ocs-operator rook-ceph-operator --replicas=0

I have asked if this is a safe operation (specifically, if our existing PVs will survive having the ocs-operator scaled back and re-deployed).

**Comment by larsks** [comment]
This is no longer an issue since the infra cluster rebuild.
