### ISSUE TITLE
Connection timeout error when trying to connect with nerc openstack cluster

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#64]
@jtriley as discussed on the call today it sounds like there may be a network ACL in place preventing services on the nerc-ocp-infra cluster from accessing OpenStack. This prevents xdmod from retrieving new usage data.

This was originally https://github.com/CCI-MOC/xdmod-cntr/issues/117, but I'm unable to transfer that issue to this repository.

**Comment by joachimweyl** [comment]
@jtriley please let us know if this change is something that you can make.

**Comment by jtriley** [comment]
This should be all set now. Let us know if you still have issues.
