### ISSUE TITLE
Build fails for sample codes available on the cluster

### ISSUE THREAD

**Issue by Milstein** [OCP-on-NERC/operations#65]
When I tried to "Create applications using samples" by using the following 2 in-built available code samples on OpenShift cluster:

https://github.com/devfile-samples/devfile-sample-python-basic.git --> Basic Python
https://github.com/nodeshift-starters/devfile-sample.git --> Basic Node.js

And also From a git repo: https://github.com/redhat-developer-demos/spring-petclinic --> spring-petclinic

For all Builds the event logs are showing the following error:
`Error starting build: an image stream cannot be used as build output because the integrated container image registry is not configured`

We might need to allow access to the [devfile community registry](https://registry.devfile.io/viewer) from our cluster.

**Comment by Milstein** [comment]
https://docs.openshift.com/container-platform/3.11/install_config/configuring_red_hat_registry.html

**Comment by larsks** [comment]
The problem is that the image registry is configured by default to use a `RollingUpdate` rollout strategy, but this isn't possible when using ReadWriteOnce storage. We need to set this to `Recreate` instead.

**Comment by larsks** [comment]
That PR should fix the image registry access issues; when applied to the cluster, we see that the image registry is now running:

```
$ k -n openshift-image-registry get pod -l docker-registry=default
NAME                              READY   STATUS    RESTARTS   AGE
image-registry-7bc48465d8-kgtrl   1/1     Running   0          107s
```

And the missing `image-registry` service has been created:

```
$ k -n openshift-image-registry get service
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
image-registry            ClusterIP   172.30.32.163   <none>        5000/TCP    2m42s
image-registry-operator   ClusterIP   None            <none>        60000/TCP   54d
```

**Comment by larsks** [comment]
@Milstein  also mentions https://ibm.github.io/openshift101/exercise-01/ as something that isn't working as expected.

**Comment by joachimweyl** [comment]
Now that the image registry is configured to use `Recreate` instead of `RollingUpdate` is this still an issue?

**Comment by larsks** [comment]
This was also blocked on https://github.com/OCP-on-NERC/operations/issues/74, which has since been completed. I'll have to re-check and confirm the current state of things.

**Comment by larsks** [comment]
This now works since we added the default limitrange to projects, although we're still tuning the limit values.
