### ISSUE TITLE
prod cluster API server needs to be externally accessible

### ISSUE THREAD

**Issue by jtriley** [OCP-on-NERC/operations#66]
Currently users would need to be on VPN in order to interact with the API server. For production we'll need to be able to access the API server from outside VPN using the `api.shift.nerc.mghpcc.org` address.

**Comment by joachimweyl** [comment]
@larsks I believe this is resolved. Is there any more work we need to do for this?

**Comment by larsks** [comment]
@joachimweyl this is all set with the most recent rebuild.
