### ISSUE TITLE
Updating the Lokistack token in vault for openshift-logging

### ISSUE THREAD

**Issue by computate** [OCP-on-NERC/operations#71]
One more step to be documented during a cluster rebuild is updating the token for openshift-logging to loki in vault: 

## Update the Lokistack token for the infra cluster

If you have done a cluster rebuild, the token used by the openshift-logging collectors will be incorrect. You will likely see errors like this in the collector pods of the `openshift-logging` namespace: 

```
2023-01-11 16:31:45 +0000 [warn]: [loki_infra] failed to write post to https://lokistack-openshift-operators-redhat.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/logs/v1/infrastructure/loki/api/v1/push (302 Found {"error":"failed to find token","errorType":"observatorium-api","status":"error"}
)
```

Log into the infra cluster in the terminal. Try finding the openshift-logging logcollector token like this:

```bash
oc --as system:admin -n openshift-logging get secret/logcollector-token -o jsonpath="{.data.token}" | base64 -d
```

With the new token value, update the `token` value in the vault here: https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/show/nerc-ocp-infra/lokistack-gateway-bearer-token

Delete the collector pods in the infra cluster: 

```bash
oc --as system:admin -n openshift-logging delete $(oc --as system:admin -n openshift-logging get pod -o name | tr '\n' ' ')
```

## Update the Lokistack token for the prod cluster

With the same token value from the infra cluster, update the `token` value in the vault here: https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/show/nerc-ocp-prod/lokistack-gateway-bearer-token

Delete the collector pods in the prod cluster: 

```bash
oc --as system:admin -n openshift-logging delete $(oc --as system:admin -n openshift-logging get pod -o name | tr '\n' ' ')
```

**Comment by jtriley** [comment]
Followed these steps and it appears logging is working again. Thanks!
