### ISSUE TITLE
Pods are failing to run due to must specify limits.cpu,limits.memory while using sample apps or S2I based deployment

### ISSUE THREAD

**Issue by Milstein** [OCP-on-NERC/operations#73]
Are there any ways we can set a limits that required on NERC OCP during launching sample apps?
As there appear to be requirements for a user to specify resource limits (limits.cpu and limits.memory), are there plans to implement default resource limits? Any image builds in the cluster fail by default; e.g.,:
From the Developer perspective,
Add > Samples > Basic Python
```
% oc get build.build.openshift.io
NAME             TYPE     FROM   STATUS                       STARTED   DURATION
python-basic-1   Docker   Git    New (CannotCreateBuildPod)
% oc describe build.build.openshift.io/python-basic-1
...
Events:
  Type      Reason      Age         From            Message
  ----      ------      ----            ----            -------
  Warning   FailedCreate    2m37s (x16 over 4m) build-controller    Error creating build pod: pods "python-basic-1-build" is forbidden: failed quota: a6f68d17679d439eb068aa0ee5dd188c-project: must specify limits.cpu,limits.memory
```
Editing the corresponding BuildConfig resource and adding in limits.cpu and limits.memory allows the build to proceed; but then a Pod fails to start unless the user manually edits resource limits for that.

**Comment by larsks** [comment]
I am closing this in favor of #74 which also proposes a possible solution.
