### ISSUE TITLE
Ensure S2I (source2image) facilities work correctly

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#74]
New users to the cluster may try to deploy applications using the `+Add` button in the "Developer" view. This will attempt to deploy code from repositories that include [`devfile`](https://devfile.io/), such as <https://github.com/devfile-samples/devfile-sample-python-basic.git>.

Scheduling pods for one of these applications will fail with:

```
Error creating build pod: pods "python-basic-1-build" is forbidden:
failed quota: lars-sandbox: must specify limits.cpu,limits.memory
```

By creating an appropriate `LimitRange` resource, we can provide default limits so that these applications will deploy correctly.

**Comment by larsks** [comment]
@Milstein from our call this morning
@knikolla tagging you because this is a coldfront integration issue

**Comment by knikolla** [comment]
@larsks As far as I know, we are setting `limits.cpu` and `limits.memory` quotas?

https://github.com/nerc-project/coldfront-plugin-cloud/blob/2df9ba19c93657f74d69c738b1f1c275209b07c5/src/coldfront_plugin_cloud/openshift.py#L14-L15

**Comment by knikolla** [comment]
@larsks Ah, I see what you mean now. I'll need to update `openshift-acct-mgt`, as that doesn't seem to support setting `LimitRange`, but only `ResourceQuota`.

**Comment by knikolla** [comment]
@jtriley @larsks I looked into this and I have a few questions before I can code a fix. 

1. Do we want to set the same `max` cpu and memory limits for all namespaces? My assumption is that since this is a per-pod limit, it would work similar to a maximum flavor of OpenStack.
2. Do we want to set a `min` at all, and what would be the use case for that?
3. Do we want to set a `default` and `defaultRequest`? If yes, what would be a good one.

**Comment by larsks** [comment]
> Do we want to set the same max cpu and memory limits for all namespaces? My assumption is that since this is a per-pod limit, it would work similar to a maximum flavor of OpenStack.

I guess using the same cpu and memory limits would for all namespaces could work, as long as we ensure the limit is always greater than whatever quotas we're applying.

> Do we want to set a min at all, and what would be the use case for that?

I'm not really sure in which situation you would want a minimum limit. Maybe (a) to prevent resource limits that are too small to be useful (like if you accidentally set a limit of `1m` cpu or something), or (b) to implicitly limit the number of containers that can be started.

> Do we want to set a default and defaultRequest? If yes, what would be a good one.

If we don't set a default or defaultRequest, then a pod that does not have an explicit resource request will effectively request the maximum (unless we specify a `min` value, in which case that will be the default), which could lead to unexpected quota consumption. I think we need a default that is smaller than the maximum.

If we set only `default`, then that will be used as the default for both `resource.requests` and `resource.limits` for containers.
