### ISSUE TITLE
Question: Does there exist a curated image registry for OpenShift-compatibale images?

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#78]
@nathanweeks asks if there exists a curated image registry or other source of images that are known to work well on OpenShift.

**Comment by dystewart** [comment]
This may be a good place to start: [Red Hat Certified Software](https://catalog.redhat.com/software/search?target_platforms=Red%20Hat%20OpenShift&type=Containerized%20product%7COperator&p=1&rows=15)

**Comment by larsks** [comment]
I think that in general the answer is "no" for the specific question that @nathanweeks is asking. A wide variety of common container images run "out of the box" on OpenShift as long as they are provided with the correct configuration. Software designed *specifically* for OpenShift is generally distributed as an [operator](https://www.redhat.com/en/technologies/cloud-computing/openshift/what-are-openshift-operators), which on the one hand is nice, because that means the configuration is all bundled up and there's a variety of lifecycle automation available, but the disadvantage is that installing operators requires cluster admin access.

For just about any application, the changes necessary to make it run on OpenShift vs. vanilla Kubernetes are minimal, and typically boil down to (a) fixing the image so that it doesn't require some sort of elevated privileges, or (b) granting the necessary privileges for the image to run in its original configuration.
