### ISSUE TITLE
rook-ceph-tools pod fails to come up due to missing keys in rook-ceph-mon secret 

### ISSUE THREAD

**Issue by jtriley** [OCP-on-NERC/operations#84]
After installing and configuring ODF on a second rebuild of the infra cluster, we noticed everything worked fine except for the rook-ceph-tools pod:

```
rook-ceph-tools-7c8c77bd96-gwqzj                   0/1     CreateContainerConfigError   0          10m
```

From `$ oc describe pod -n openshift-storage rook-ceph-tools-xxxx`:
```
  Warning  Failed     7m56s (x12 over 10m)  kubelet            Error: couldn't find key ceph-username in Secret openshift-storage/rook-ceph-mon
```

Inspecting the `rook-ceph-mon` secret via `$ oc get secret -n openshift-storage rook-ceph-mon -o yaml` confirms that neither of the following environment variables it's expecting exist:

```
$ oc describe pod -n openshift-storage rook-ceph-tools-xxxx
...
    Environment:
      ROOK_CEPH_USERNAME:  <set to the key 'ceph-username' in secret 'rook-ceph-mon'>  Optional: false
      ROOK_CEPH_SECRET:    <set to the key 'ceph-secret' in secret 'rook-ceph-mon'>    Optional: false
...
```

**Comment by naved001** [comment]
looks like the same problem is on the `nerc-ocp-prod` cluster.

**Comment by jtriley** [comment]
It might just be that this container isn't supported on ODF in external mode. I know some of ODF's features aren't available in external mode 🤷

**Comment by jtriley** [comment]
If that's the case we should patch the `OCSInit` with `enableCephTools: false`

**Comment by naved001** [comment]
On MOC's `ocp-prod` cluster we are running the older OCS 4.8 in external mode and that does not have this problem. The secret `rook-ceph-mon` includes the  key `ceph-username`, and the tools pod is running without issues.

**Comment by jtriley** [comment]
Oddly another rebuild to OpenShift 4.10.47 seems to have fixed it 🤷 . No change to the `rook-ceph-mon` secret. Maybe ODF version but not sure anything has changed on that front in the past few days? Will look into it.

**Comment by joachimweyl** [comment]
Is this still an issue?

**Comment by jtriley** [comment]
Haven't seen this issue again after several rebuilds of both the infra and prod cluster. Closing
