### ISSUE TITLE
Update OpenShift on the NERC Test Cluster

### ISSUE THREAD

**Issue by joachimweyl** [OCP-on-NERC/operations#85]
It is important to have the test cluster running the same version of OpenShift as the Production cluster.
This will also be helpful to ensure that RHODS can use the test cluster as a first round of testing to see if it will work on the production cluster.

**Comment by dystewart** [comment]
Test cluster is up and running on all test cluster nodes, see kubeadmin and endpoint details in vault.

**Comment by dystewart** [comment]
Since OpenShift has been installed and updated on the test cluster, I'm closing this issue and opening a new one regarding configuring it for RHODS. 

Here is the new issue: [https://github.com/OCP-on-NERC/operations/issues/92](https://github.com/OCP-on-NERC/operations/issues/92)
