### ISSUE TITLE
Do we need to rebuild the cluster to add a second ODF storage pool

### ISSUE THREAD

**Issue by joachimweyl** [OCP-on-NERC/operations#89]
NESE created an SSD pool for us to use with the NERC OpenShift Production cluster.
Will we need to rebuild the cluster to include a second ODF storage pool?

**Comment by joachimweyl** [comment]
@jtriley I have assigned this to you. Please leverage MOC team members as needed.

**Comment by jtriley** [comment]
We don't need to rebuild to use an additional pool. It turns out that to use another pool on the same ceph cluster is simply a matter of defining another rbd storageclass referencing the new pool and secrets. I've set this up on the prod cluster and notified folks that are benchmarking in #6
