### ISSUE TITLE
To investigate with OCP resource quota attributes

### ISSUE THREAD

**Issue by Milstein** [OCP-on-NERC/operations#97]
In our OCP cluster Resource Quotas are only set for:
> limits.cpu
> limits.ephemeral-storage
> limits.memory

I found out that by default RH Sandbox has many other useful Quota attributes enabled and tracked/project as shown in the screenshot here. Can we also investigate and see if some of them can be useful for NERC users i.e. storage. 

![ocp-project-resource-quotas](https://user-images.githubusercontent.com/144645/227597081-5a3ddfee-2a33-4c07-98af-0efbca8c53d4.png)

**Comment by joachimweyl** [comment]
@larsks with the Noobaa issue that cropped up is this still an issue we plan to resolve this sprint?

**Comment by larsks** [comment]
@joachimweyl @Milstein I would actually like to close this issue -- I think it's too broad to be actionable.

If there are specific quotas you would like to enforce on new projects, you should write up a proposal that describes specifically what limits you want to apply and how that will be managed through coldfront.

I think folks from the NERC team -- including @jtriley, @aabaris, and Scott Yokel -- would need to approve the quotas before we start looking at implementation work.

**Comment by knikolla** [comment]
@Milstein https://github.com/nerc-project/coldfront-plugin-cloud/commit/5c0a5b8a5dd6041c8842a26cfc58c015b6391f87 recently merged and added support for storage and persistentvolumeclaims. So it's not just 3 now. 

If you have others in mind, open an issue in `nerc-project/coldfront-plugin-cloud` and we can add it fairly easily.
